### ISSUE TITLE
Ensemble gene ID with many protein ID? How can we know?

### ISSUE THREAD

**Issue by lkhangkv1995** [CCSB-DFCI/HuRI_paper#17]
Thank you for your paper. I hope to use the dataset (and cite your paper) in the future.

I would like to ask whether we have protein ID instead of gene ID, or whether we know which exact isoform are used in the gene ID? or am I missing something in your repository?

My goal is to pull the amino acid sequences and analyze them. But there are different isoforms (with different protein ID) ending up within the same gene (same gene ID). For example, like ENSG00000140416 gene has 18 isoforms.

Thank you very much.

**Comment by llambourne** [comment]
Thanks for your interest. 

We have the PSI-MI tab format for the HuRI dataset available here: 
http://www.interactome-atlas.org/download
which has either the uniprot ac at the isoform level or the ensembl protein and transcript IDs. Does that work? If it doesn't, then I can send you the exact amino acid sequences of the clones used together with the dataset with our internal cloned ORF IDs.

**Comment by lkhangkv1995** [comment]
Thank you for the reply.

Thanks to your advice, I found the protein ID as I wished.

This is my mistake. I got to the website but then used the .csv file instead. Thank you for letting me know. 
If our project goes well, your paper is definitely on the reference.
